package com.coreintra.auth.crypto;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Hashing for <em>high-entropy</em> secrets: recovery codes and API keys.
 *
 * <h2>Why SHA-256 and not bcrypt or argon2</h2>
 *
 * <p>A slow KDF exists to make guessing a low-entropy human-chosen secret
 * expensive. Everything hashed here is generated by {@link SecureRandom} with
 * at least 128 bits of entropy, so guessing is already infeasible by many
 * orders of magnitude and iteration count adds nothing an attacker notices.
 *
 * <p>This reasoning holds <b>only</b> because these values are machine-generated.
 * It would be wrong for anything a person chooses — which is one more reason
 * this system has no passwords at all (ADR 0006). If a user-chosen secret is
 * ever introduced, it does not belong in this class.
 *
 * <p>Each value gets its own random salt, so identical recovery codes issued to
 * two accounts do not produce identical rows.
 */
public final class SecretHasher {

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final int SALT_BYTES = 16;
    private static final String ALGORITHM = "SHA-256";
    private static final String PREFIX = "s256";

    private SecretHasher() {
    }

    /** @return {@code s256$<base64 salt>$<base64 hash>} */
    public static String hash(String plaintext) {
        byte[] salt = new byte[SALT_BYTES];
        RANDOM.nextBytes(salt);
        byte[] digest = digest(salt, plaintext);
        return PREFIX + "$" + encode(salt) + "$" + encode(digest);
    }

    /**
     * Constant-time verification.
     *
     * <p>Returns false rather than throwing on a malformed stored value: a
     * corrupt row must fail closed, not crash the sign-in path.
     */
    public static boolean matches(String plaintext, String stored) {
        if (plaintext == null || stored == null) {
            return false;
        }
        String[] parts = stored.split("\\$");
        if (parts.length != 3 || !PREFIX.equals(parts[0])) {
            return false;
        }
        byte[] salt;
        byte[] expected;
        try {
            salt = Base64.getDecoder().decode(parts[1]);
            expected = Base64.getDecoder().decode(parts[2]);
        } catch (IllegalArgumentException e) {
            return false;
        }
        return MessageDigest.isEqual(expected, digest(salt, plaintext));
    }

    private static byte[] digest(byte[] salt, String plaintext) {
        try {
            MessageDigest sha = MessageDigest.getInstance(ALGORITHM);
            sha.update(salt);
            sha.update(plaintext.getBytes(StandardCharsets.UTF_8));
            return sha.digest();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 unavailable in this JRE", e);
        }
    }

    private static String encode(byte[] data) {
        return Base64.getEncoder().withoutPadding().encodeToString(data);
    }

    /**
     * A URL-safe random token.
     *
     * @param bytes entropy in bytes; 16 is the floor for anything bearer-like
     */
    public static String randomToken(int bytes) {
        if (bytes < 16) {
            throw new IllegalArgumentException(
                    "a bearer secret needs at least 128 bits of entropy; asked for " + bytes * 8);
        }
        byte[] material = new byte[bytes];
        RANDOM.nextBytes(material);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(material);
    }
}
